### ISSUE TITLE
bug: there's a typo in the README

### ISSUE THREAD

**Issue by Vyvy-vi** [SKULLXL/SKULLXL#1]
`Certifications` is typoed as `Cetrticfications`
![Screenshot 2020-11-23 at 8 55 31 PM](https://user-images.githubusercontent.com/62864373/99980924-c9f93f00-2dce-11eb-99c3-9609dd8567a8.png)

**Comment by SKULLXL** [comment]
Thanks for finding the typo out 💙 . I'll deal with it rn.

**Comment by SKULLXL** [comment]
Fixed. Again thanks for finding it.
